import {Injectable} from '@angular/core';
import {HousingLocation} from './housinglocation';
@Injectable({
  providedIn: 'root',
})
export class HousingService {
  url = 'http://localhost:3000/locations';
  async getAllHousingLocations(): Promise<HousingLocation[]> {
    const data = await fetch(this.url);
    return (await data.json()) ?? [];
  }
  async getHousingLocationById(id: number): Promise<HousingLocation | undefined> {
    const data = await fetch(`${this.url}/${id}`);
    return (await data.json()) ?? {};
  }
  submitApplication(firstName: string, lastName: string, email: string) {
    // tslint:disable-next-line
    // Generated by Copilot
    console.log(firstName, lastName, email);

    // Supprimer le message 'Email is invalid' s'il est affiché sur la page
    const messageInvalide = document.querySelector('p.email-invalid');
    if (messageInvalide) {
      messageInvalide.remove();
    }
    const message = `${firstName} ${lastName} ${email} applied !`;
    const messageElement = document.createElement('div');
    messageElement.textContent = message;
    document.body.appendChild(messageElement);
  }
}